# -*- coding: utf-8 -*-
countries = {
u"Andorra": [u"Andorra",u"Andorra",u"Andorra",u"Andorra"],
u"Emiratos Arabes": [u"Emiratos Árabes Unidos",u"United Arab Emirates",u"Vereinigte Arabische Emirate",u"Unió dels Emirats Àrabs"],
u"Afganistán": [u"Afganistán",u"Afghanistan",u"Afghanistan",u"Afganistan"],
u"Antigua & Barbuda": [u"Antigua y Barbuda",u"Antigua and Barbuda",u"Antigua und Barbuda",u"Antigua i Barbuda"],
u"Anguilla": [u"Anguila",u"Anguilla",u"Anguilla",u"Anguilla"],
u"Albania": [u"Albania",u"Albania",u"Albanien",u"Albània"],
u"Armenia": [u"Armenia",u"Armenia",u"Armenien",u"Armènia"],
u"Antillas holandesas": [u"Antillas Neerlandesas",u"Netherlands Antilles",u"Niederländische Antillen",u"Antilles Holandeses"],
u"Angola": [u"Angola",u"Angola",u"Angola",u"Angola"],
u"Argentina": [u"Argentina",u"Argentina",u"Argentinien",u"Argentina"],
u"Austria": [u"Austria",u"Austria",u"Österreich",u"Àustria"],
u"Australia": [u"Australia",u"Australia",u"Australien",u"Austràlia"],
u"Aruba": [u"Aruba",u"Aruba",u"Aruba",u"Aruba"],
u"Azerbaiján": [u"Azerbaiyán",u"Azerbaijan",u"Aserbaidschan",u"Azerbaitjan"],
u"Bosnia Herzegovina": [u"Bosnia y Hercegovina",u"Bosnia and Herzegovina",u"Bosnien und Herzegowina",u"Bòsnia i Hercegovina"],
u"Barbados": [u"Barbados",u"Barbados",u"Barbados",u"Barbados"],
u"Bangla Desh": [u"Bangladesh",u"Bangladesh",u"Bangladesch",u"Bangla Desh"],
u"Bhután": [u"Bután",u"Bhutan",u"Bhutan",u"Bhutan"],
u"Bélgica": [u"Bélgica",u"Belgium",u"Belgien",u"Bèlgica"],
u"Burkina Faso": [u"Burkina Faso",u"Burkina Faso",u"Burkina Faso",u"Burkina Faso"],
u"Bulgaria": [u"Bulgaria",u"Bulgaria",u"Bulgarien",u"Bulgària"],
u"Bahrain": [u"Bahráin",u"Bahrain",u"Bahrain",u"Bahrain"],
u"Burundi": [u"Burundi",u"Burundi",u"Burundi",u"Burundi"],
u"Benin": [u"Benín",u"Benin",u"Benin",u"Benín"],
u"Bermudas": [u"Bermudas",u"Bermuda",u"die Bermudas",u"Bermuda"],
u"Brunei": [u"Brunéi",u"Brunei",u"Brunei Darussalam",u"Brunei"],
u"Bolivia": [u"Bolivia",u"Bolivia",u"Bolivien",u"Bolívia"],
u"Brasil": [u"Brasil",u"Brazil",u"Brasilien",u"Brasil"],
u"Bahamas": [u"Bahamas",u"The Bahamas",u"Bahamas",u"Bahames"],
u"Botswana": [u"Botsuana",u"Botswana",u"Botsuana",u"Botswana"],
u"Bielorrusia": [u"Bielorrusia",u"Belarus",u"Belarus",u"Bielorússia"],
u"Belice": [u"Belice",u"Belize",u"Belize",u"Belize"],
u"Canadá": [u"Canadá",u"Canada",u"Kanada",u"Canadà"],
u"Congo (Kinshasa)": [u"República Democrática del Congo",u"Democratic Republic of the Congo",u"Demokratische Republik Kongo",u"Congo, República Democràtica del"],
u"República Centroafricana": [u"República Centroafricana",u"Central African Republic",u"Zentralafrikanische Republik",u"República Centreafricana"],
u"Congo (Brazzaville)": [u"Congo",u"Congo",u"Kongo",u"Congo"],
u"Suiza": [u"Suiza",u"Switzerland",u"Schweiz",u"Suïssa"],
u"Costa de Marfil": [u"Costa de Marfil",u"Côte d'Ivoire",u"Côte d'Ivoire",u"Costa d'Ivori"],
u"Islas Cook": [u"Islas Cook",u"Cook Islands",u"Cookinseln",u"Illes Cook"],
u"Chile": [u"Chile",u"Chile",u"Chile",u"Xile"],
u"Camerún": [u"Camerún",u"Cameroon",u"Kamerun",u"Camerun"],
u"China": [u"China",u"China",u"China",u"Xina"],
u"Colombia": [u"Colombia",u"Colombia",u"Kolumbien",u"Colòmbia"],
u"Costa Rica": [u"Costa Rica",u"Costa Rica",u"Costa Rica",u"Costa Rica"],
u"Serbia & Montenegro": [u"Serbia & Montenegro",u"Serbia & Montenegro",u"Serbien und Montenegro",u"Sèrbia i Montenegro"],
u"Cuba": [u"Cuba",u"Cuba",u"Kuba",u"Cuba"],
u"Cabo Verde": [u"Cabo Verde",u"Cape Verde",u"Kap Verde",u"Cap Verd"],
u"Chipre": [u"Chipre",u"Cyprus",u"Zypern",u"Xipre"],
u"República Checa": [u"República Checa",u"Czech Republic",u"Tschechische Republik",u"República Txeca"],
u"Alemania": [u"Alemania",u"Germany",u"Deutschland",u"Alemanya"],
u"Djibouti": [u"Yibuti",u"Djibouti",u"Dschibuti",u"Djibouti"],
u"Dinamarca": [u"Dinamarca",u"Denmark",u"Dänemark",u"Dinamarca"],
u"Dominica": [u"Dominica",u"Dominica",u"Dominica",u"Dominica"],
u"República Dominicana": [u"República Dominicana",u"Dominican Republic",u"Dominikanische Republik",u"República Dominicana"],
u"Argelia": [u"Argelia",u"Algeria",u"Algerien",u"Algèria"],
u"Ecuador": [u"Ecuador",u"Ecuador",u"Ecuador",u"Equador"],
u"Estonia": [u"Estonia",u"Estonia",u"Estland",u"Estònia"],
u"Egipto": [u"Egipto",u"Egypt",u"Ägypten",u"Egipte"],
u"Sahara": [u"Sáhara Occidental",u"Western Sahara",u"Westsahara",u"Sàhara Occidental"],
u"Eritrea": [u"Eritrea",u"Eritrea",u"Eritrea",u"Eritrea"],
u"España": [u"España",u"Spain",u"Spanien",u"Espanya"],
u"Etiopía": [u"Etiopía",u"Ethiopia",u"Äthiopien",u"Etiòpia"],
u"Finlandia": [u"Finlandia",u"Finland",u"Finnland",u"Finlàndia"],
u"Fiji": [u"Fiyi",u"Fiji",u"Fidschi",u"Fiji"],
u"Islas Malvinas": [u"Islas Malvinas",u"Falkland Islands",u"Falklandinseln",u"Illes Malvines (Falkland)"],
u"Micronesia": [u"Micronesia",u"Micronesia",u"Mikronesien",u"Micronèsia, Estats Federats de"],
u"Islas Faroe": [u"Islas Feroe",u"Faeroe Islands",u"Färöer",u"Illes Fèroe"],
u"Francia": [u"Francia",u"France",u"Frankreich",u"França"],
u"Gabón": [u"Gabón",u"Gabon",u"Gabun",u"Gabon"],
u"Gran Bretaña": [u"Reino Unido",u"United Kingdom",u"Vereinigtes Königreich",u"Regne Unit"],
u"Granada": [u"Granada",u"Grenada",u"Grenada",u"Grenada"],
u"Georgia": [u"Georgia",u"Georgia",u"Georgien",u"Geòrgia"],
u"Guayana Fr.": [u"Guayana Francesa",u"French Guiana",u"Französisch-Guayana",u"Guaiana Francesa"],
u"Ghana": [u"Ghana",u"Ghana",u"Ghana",u"Ghana"],
u"Gibraltar": [u"Gibraltar",u"Gibraltar",u"Gibraltar",u"Gibraltar"],
u"Groenlandia": [u"Groenlandia",u"Greenland",u"Grönland",u"Groenlàndia"],
u"Gambia": [u"Gambia",u"The Gambia",u"Gambia",u"Gàmbia"],
u"Guinea": [u"Guinea",u"Guinea",u"Guinea",u"Guinea"],
u"Guadalupe": [u"Guadalupe",u"Guadeloupe",u"Guadeloupe",u"Guadalupe"],
u"Guinea ecuatorial": [u"Guinea Ecuatorial",u"Equatorial Guinea",u"Äquatorialguinea",u"Guinea Equatorial"],
u"Grecia": [u"Grecia",u"Greece",u"Griechenland",u"Grècia"],
u"Guatemala": [u"Guatemala",u"Guatemala",u"Guatemala",u"Guatemala"],
u"Guinea-Bissau": [u"Guinea-Bissau",u"Guinea-Bissau",u"Guinea-Bissau",u"Guinea Bissau"],
u"Guyana": [u"Guyana",u"Guyana",u"Guyana",u"Guyana"],
u"Hong Kong": [u"Hong Kong",u"Hong Kong",u"Hongkong",u"Hong Kong"],
u"Honduras": [u"Honduras",u"Honduras",u"Honduras",u"Hondures"],
u"Croacia": [u"Croacia",u"Croatia",u"Kroatien",u"Croàcia"],
u"Haití": [u"Haití",u"Haiti",u"Haiti",u"Haití"],
u"Hungría": [u"Hungría",u"Hungary",u"Ungarn",u"Hongria"],
u"Indonesia": [u"Indonesia",u"Indonesia",u"Indonesien",u"Indonèsia"],
u"Irlanda": [u"Irlanda",u"Ireland",u"Irland",u"Irlanda"],
u"Israel": [u"Israel",u"Israel",u"Israel",u"Israel"],
u"India": [u"India (la)",u"India",u"Indien",u"Índia"],
u"Irak": [u"Iraq",u"Iraq",u"Irak",u"Iraq"],
u"Irán": [u"Irán",u"Iran",u"Iran",u"Iran"],
u"Islandia": [u"Islandia",u"Iceland",u"Island",u"Islàndia"],
u"Italia": [u"Italia",u"Italy",u"Italien",u"Itàlia"],
u"Jamaica": [u"Jamaica",u"Jamaica",u"Jamaika",u"Jamaica"],
u"Jordania": [u"Jordania",u"Jordan",u"Jordanien",u"Jordània"],
u"Japón": [u"Japón",u"Japan",u"Japan",u"Japó"],
u"Kenya": [u"Kenia",u"Kenya",u"Kenia",u"Kenya"],
u"Kirguizistán": [u"Kirguizistán",u"Kyrgyzstan",u"Kirgisistan",u"Kirguizistan"],
u"Camboya": [u"Camboya",u"Cambodia",u"Kambodscha",u"Cambodja"],
u"Kiribati": [u"Kiribati",u"Kiribati",u"Kiribati",u"Kiribati"],
u"Comoros": [u"Comoras",u"Comoros",u"Komoren",u"Comores"],
u"Saint Kitts & Nevis": [u"San Cristóbal y Nieves",u"Saint Kitts and Nevis",u"St. Kitts und Nevis",u"Saint Christopher i Nevis"],
u"Corea del Norte": [u"Corea del Norte",u"North Korea",u"Demokratische Volksrepublik Korea",u"Corea del Nord"],
u"Corea del Sur": [u"Corea del Sur",u"South Korea",u"Republik Korea",u"Corea del Sud"],
u"Kuwait": [u"Kuwait",u"Kuwait",u"Kuwait",u"Kuwait"],
u"Islas Caimán": [u"Islas Caimán",u"Cayman Islands",u"Kaimaninseln",u"Illes Caiman"],
u"Kazajstán": [u"Kazajistán",u"Kazakhstan",u"Kasachstan",u"Kazakhstan"],
u"Laos": [u"Laos",u"Laos",u"Laos",u"Laos"],
u"Líbano": [u"Líbano",u"Lebanon",u"Libanon",u"Líban"],
u"Santa Lucia": [u"Santa Lucía",u"Saint Lucia",u"St. Lucia",u"Saint Lucia"],
u"Liechtenstein": [u"Liechtenstein",u"Liechtenstein",u"Liechtenstein",u"Liechtenstein"],
u"Sri Lanka": [u"Sri Lanka",u"Sri Lanka",u"Sri Lanka",u"Sri Lanka"],
u"Liberia": [u"Liberia",u"Liberia",u"Liberia",u"Libèria"],
u"Lesotho": [u"Lesoto",u"Lesotho",u"Lesotho",u"Lesotho"],
u"Lituania": [u"Lituania",u"Lithuania",u"Litauen",u"Lituània"],
u"Luxemburgo": [u"Luxemburgo",u"Luxembourg ",u"Luxemburg",u"Luxemburg"],
u"Letonia": [u"Letonia",u"Latvia",u"Lettland",u"Letònia"],
u"Libia": [u"Libia",u"Libya",u"Libyen",u"Líbia"],
u"Marruecos": [u"Marruecos",u"Morocco",u"Marokko",u"Marroc"],
u"Monaco": [u"Mónaco",u"Monaco",u"Monaco",u"Mònaco"],
u"Moldavia": [u"Moldavia",u"Moldova",u"Republik Moldau",u"Moldàvia"],
u"Madagascar": [u"Madagascar",u"Madagascar",u"Madagaskar",u"Madagascar"],
u"Islas Marshall": [u"Islas Marshall",u"Marshall Islands",u"Marshallinseln",u"Illes Marshall"],
u"Macedonia": [u"Macedonia",u"Republic of Macedonia",u"Republik Mazedonien",u"Macedònia"],
u"Mali": [u"Malí",u"Mali",u"Mali",u"Mali"],
u"Myanmar (Birmania)": [u"Birmania; Myanmar",u"Myanmar",u"Myanmar",u"Myanmar"],
u"Mongolia": [u"Mongolia",u"Mongolia",u"Mongolei",u"Mongòlia"],
u"Martinique": [u"Martinica",u"Martinique",u"Martinique",u"Martinica"],
u"Mauritania": [u"Mauritania",u"Mauritania",u"Mauretanien",u"Mauritània"],
u"Montserrat": [u"Montserrat",u"Montserrat",u"Montserrat",u"Montserrat"],
u"Malta": [u"Malta",u"Malta",u"Malta",u"Malta"],
u"Mauricio": [u"Mauricio",u"Mauritius",u"Mauritius",u"Maurici"],
u"Maldivas": [u"Maldivas",u"Maldives",u"Malediven",u"Maldives"],
u"Malawi": [u"Malaui",u"Malawi",u"Malawi",u"Malawi"],
u"México": [u"México",u"Mexico",u"Mexiko",u"Mèxic"],
u"Malasia": [u"Malasia",u"Malaysia",u"Malaysia",u"Malàisia"],
u"Mozambique": [u"Mozambique",u"Mozambique",u"Mosambik",u"Moçambic|"],
u"Namibia": [u"Namibia",u"Namibia",u"Namibia",u"Namíbia"],
u"Nueva Caledonia": [u"Nueva Caledonia",u"New Caledonia",u"Neukaledonien",u"Nova Caledònia"],
u"Níger": [u"Níger",u"Niger",u"Niger",u"Níger"],
u"Islas Norfolk": [u"Isla Norfolk",u"Norfolk Island",u"Norfolkinsel",u"Illa Norfolk"],
u"Nigeria": [u"Nigeria",u"Nigeria",u"Nigeria",u"Nigèria"],
u"Nicaragua": [u"Nicaragua",u"Nicaragua",u"Nicaragua",u"Nicaragua"],
u"Países Bajos": [u"Países Bajos",u"Netherlands",u"Niederlande",u"Països Baixos"],
u"Noruega": [u"Noruega",u"Norway",u"Norwegen",u"Noruega"],
u"Nepal": [u"Nepal",u"Nepal",u"Nepal",u"Nepal"],
u"Nauru": [u"Nauru",u"Nauru",u"Nauru",u"Nauru"],
u"Niue": [u"Niue",u"Niue",u"Niue",u"Niue"],
u"Nueva Zelanda": [u"Nueva Zelanda",u"New Zealand",u"Neuseeland",u"Nova Zelanda"],
u"Omán": [u"Omán",u"Oman",u"Oman",u"Oman"],
u"Panamá": [u"Panamá",u"Panama",u"Panama",u"Panamà"],
u"Perú": [u"Perú",u"Peru",u"Peru",u"Perú"],
u"Polinesia": [u"Polinesia Francesa",u"French Polynesia",u"Französisch-Polynesien",u"Polinèsia Francesa"],
u"Papua Nueva Guinea": [u"Papúa-Nueva Guinea",u"Papua New Guinea",u"Papua-Neuguinea",u"Papua Nova Guinea"],
u"Filipinas": [u"Filipinas",u"Philippines",u"Philippinen",u"Filipines"],
u"Pakistán": [u"Pakistán",u"Pakistan",u"Pakistan",u"Pakistan"],
u"Polonia": [u"Polonia",u"Poland",u"Polen",u"Polònia"],
u"San Pierre & Miquelon": [u"San Pedro y Miquelón",u"Saint Pierre and Miquelon",u"St. Pierre und Miquelon",u"Saint Pierre i Miquelon"],
u"Palestina": [u"Palestina",u"Palestine",u"Palestine",u"Palestina"],
u"Portugal": [u"Portugal",u"Portugal",u"Portugal",u"Portugal"],
u"Palau": [u"Palaos",u"Palau",u"Palau",u"Palau"],
u"Paraguay": [u"Paraguay",u"Paraguay",u"Paraguay",u"Paraguai"],
u"Qatar": [u"Qatar",u"Qatar",u"Katar",u"Qatar"],
u"Reunión": [u"Reunión",u"Reunion",u"Reunion",u"Reunion"],
u"Rumanía": [u"Rumanía",u"Romania",u"Rumänien",u"Romania"],
u"Rusia": [u"Rusia",u"Russia",u"Russische Föderation",u"Rússia"],
u"Ruanda": [u"Ruanda",u"Rwanda",u"Ruanda",u"Rwanda"],
u"Arabia Saudita": [u"Arabia Saudí",u"Saudi Arabia",u"Saudi-Arabien",u"Aràbia Saudita"],
u"Islas Salomón": [u"Islas Salomón",u"Solomon Islands",u"Salomonen",u"Illes Salomó"],
u"Seychelles": [u"Seychelles",u"Seychelles",u"Seychellen",u"Seychelles"],
u"Sudán": [u"Sudán",u"Sudan",u"Sudan",u"Sudan"],
u"Suecia": [u"Suecia",u"Sweden",u"Schweden",u"Suècia"],
u"Singapur": [u"Singapur",u"Singapore",u"Singapur",u"Singapur"],
u"Santa Helena": [u"Santa Helena",u"Saint Helena",u"St. Helena",u"Saint Helena"],
u"Eslovenia": [u"Eslovenia",u"Slovenia",u"Slowenien",u"Eslovènia"],
u"Eslovaquia": [u"Eslovaquia",u"Slovakia",u"Slowakei",u"Eslovàquia"],
u"Sierra Leona": [u"Sierra Leona",u"Sierra Leone",u"Sierra Leone",u"Sierra Leone"],
u"San Marino": [u"San Marino",u"San Marino",u"San Marino",u"San Marino"],
u"Senegal": [u"Senegal",u"Senegal",u"Senegal",u"Senegal"],
u"Somalia": [u"Somalia",u"Somalia",u"Somalia",u"Somàlia"],
u"Suriname": [u"Surinam",u"Suriname",u"Suriname",u"Surinam"],
u"Santo Tomé & Príncipe": [u"Santo Tomé y Príncipe",u"São Tomé and Príncipe",u"São Tomé und Príncipe",u"Sao Tomé i Príncipe"],
u"El Salvador": [u"El Salvador",u"El Salvador",u"El Salvador",u"El Salvador"],
u"Siria": [u"Siria",u"Syria",u"Syrien",u"Síria"],
u"Swazilandia": [u"Suazilandia",u"Swaziland",u"Swasiland",u"Swazilàndia"],
u"Turcos & Caicos": [u"Islas Turcas y Caicos",u"Turks and Caicos Islands",u"Turks- und Caicosinseln",u"Illes Turks i Caicos"],
u"Chad": [u"Chad",u"Chad",u"Tschad",u"Txad"],
u"French Southern Lands": [u"Territorios Australes Franceses",u"French Southern Territories",u"Französische Gebiete (Ind. Oz.)",u"Territoris Francesos del Sud"],
u"Togo": [u"Togo",u"Togo",u"Togo",u"Togo"],
u"Tailandia": [u"Tailandia",u"Thailand",u"Thailand",u"Tailàndia"],
u"Tadschikistan": [u"Tayikistán",u"Tajikistan",u"Tadschikistan",u"Tadjikistan"],
u"Tokelau": [u"Tokelau",u"Tokelau",u"Tokelau",u"Tokelau"],
u"Timor oriental": [u"Timor Oriental",u"East Timor",u"Osttimor",u"Timor-Leste"],
u"Turkmenistan": [u"Turkmenistán",u"Turkmenistan",u"Turkmenistan",u"Turkmenistan"],
u"Túnez": [u"Túnez",u"Tunisia",u"Tunesien",u"Tunísia"],
u"Tonga": [u"Tonga",u"Tonga",u"Tonga",u"Tonga"],
u"Turquía": [u"Turquía",u"Turkey",u"Türkei",u"Turquia"],
u"Trinidad & Tabago": [u"Trinidad y Tobago",u"Trinidad and Tobago",u"Trinidad und Tobago",u"Trinitat i Tobago"],
u"Tuvalu": [u"Tuvalu",u"Tuvalu",u"Tuvalu",u"Tuvalu"],
u"Taiwán": [u"Taiwán",u"Taiwan",u"Taiwan",u"Taiwan"],
u"Tanzania": [u"Tanzania",u"Tanzania",u"Tansania",u"Tanzània"],
u"Ucrania": [u"Ucrania",u"Ukraine",u"Ukraine",u"Ucraïna"],
u"Uganda": [u"Uganda",u"Uganda",u"Uganda",u"Uganda"],
u"Uruguay": [u"Uruguay",u"Uruguay",u"Uruguay",u"Uruguai"],
u"Uzbekistan": [u"Uzbekistán",u"Uzbekistan",u"Usbekistan",u"Uzbekistan"],
u"Vaticano": [u"El Vaticano",u"Vatican City",u"Vatikanstadt",u"Ciutat del Vaticà"],
u"San Vincente & Granadinas": [u"San Vicente y las Granadinas",u"Saint Vincent and the Grenadines",u"St. Vincent und die Grenadinen",u"Saint Vincent i les Grenadines"],
u"Venezuela": [u"Venezuela",u"Venezuela",u"Venezuela",u"Veneçuela"],
u"Is. Vírgenes": [u"Islas Vírgenes Británicas",u"British Virgin Islands",u"Britische Jungferninseln",u"Illes Verge Britàniques"],
u"Vietnam": [u"Vietnam",u"Vietnam",u"Vietnam",u"Vietnam"],
u"Vanuatu": [u"Vanuatu",u"Vanuatu",u"Vanuatu",u"Vanuatu"],
u"Wallis & Futuna": [u"Wallis y Futuna",u"Wallis and Futuna",u"Wallis und Futuna",u"Wallis i Futuna"],
u"Samoa-oeste": [u"Samoa",u"Samoa",u"Samoa",u"Samoa"],
u"Yemen": [u"Yemen",u"Yemen",u"Jemen",u"Iemen"],
u"Mayotte": [u"Mayotte",u"Mayotte",u"Mayotte",u"Mayotte"],
u"Sudáfrica": [u"Sudáfrica",u"South Africa",u"Südafrika",u"Sud-àfrica"],
u"Zambia": [u"Zambia",u"Zambia",u"Sambia",u"Zàmbia"],
u"Zimbabwe": [u"Zimbabue",u"Zimbabwe",u"Simbabwe",u"Zimbabwe"] }

cata_reg = {
        u"España": u"Espanya", 
        u"Baleares": u"Illes Balears",
        u"La Rioja": u"La Rioja",   
        u"Madrid": u"Comunitat de Madrid",
        u"Murcia": u"Regió de Múrcia",
        u"Navarra": u"Navarra",
        u"Asturias": u"Principat d'Astúries",
        u"Cantabria": u"Cantàbria",
        u"Andalucía": u"Andalusia",
        u"Aragón": u"Aragó",
        u"Canarias": u"Illes Canàries",
        u"Castilla-La Mancha": u"Castella - la Manxa",
        u"Castilla y León": u"Castella i Lleó",
        u"Cataluña": u"Catalunya",
        u"Extremadura": u"Extremadura",
        u"Galicia": u"Galícia",
        u"Pais Vasco": u"País Basc",
        u"Valencia": u"País Valencià" }

def install(lang):
    global countries
    langs = { 'es': 0, 'en': 1, 'de': 2, 'ca': 3 }
    l = langs[lang]
    temp = {}
    for k in countries.keys():
        temp[k] = countries[k][l]
    countries = temp
    countries[u'USA'] = u'USA'
    import __builtin__
    __builtin__.__dict__['t'] = trad


def trad(name):
    try:
        return countries[name]
    except KeyError:
        return name
